export const techKnwledege = [
  {
    id: 1,
    title: 'HTML',
    icon: '',
    obtained: 3,
    description: 'Yeah I know about semantic tags',
    color: '#c41d7f',
    background: '#fff0f6',
    borderColor: '#ffadd2',
  },
  {
    id: 2,
    title: 'CSS',
    icon: '',
    obtained: 3,
    description: ' I have got this uncanny knack for creating designs that snugly hug every device and screen size out there.',
    color: '#c41d7f',
    background: '#fff0f6',
    borderColor: '#ffadd2',
  },
  {
    id: 3,
    title: 'Javascript',
    icon: '',
    obtained: 3,
    description: 'Promises? Oh, those are not my style, unlike JavaScript acrobatics.',
    color: '#c41d7f',
    background: '#fff0f6',
    borderColor: '#ffadd2',
  },
  {
    id: 4,
    title: 'React',
    icon: '',
    obtained: 3,
    description: "Guess what? I've mastered the useState and useEffect duo, and now I'm on a quest to unravel the mysteries of when not to unleash their powers.",
    color: '#c41d7f',
    background: '#fff0f6',
    borderColor: '#ffadd2',
  },
  {
    id: 5,
    title: 'Next JS',
    icon: '',
    obtained: 3,
    description: "Embarking on a wild adventure in the realms of Next.js  because who needs sleep when you've got server-side sorcery to learn?",
    color: '#c41d7f',
    background: '#fff0f6',
    borderColor: '#ffadd2',
  },
]